4-Python/django/belt_reviewer/apps/my_app/urls.py
from django.conf.urls import url
from . import views
# from views import *

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register', views.register, name='register'),
    url(r'^landing_page$', views.landing_page, name='landing_page'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^new_book$', views.show_add_book_page, name='new_book'),
    url(r'^process_add_book$', views.process_add_book, name='process_add_book'),
    url(r'^book/(?P<book_id>\d+)$', views.show_book_page, name='book_page'),
    url(r'^user/(?P<user_id>\d+)$', views.show_user_profile, name='user_page'),
    url(r'^add_review/(?P<book_id>\d+)$', views.add_review, name='add_review'),
    url(r'^delete_review/(?P<review_id>\d+)$', views.delete_review, name='delete_review'),
    url(r'^add_to_my_favorites/(?P<book_id>\d+)$', views.add_to_my_favorites, name='add_to_my_favorites')    
]

4-Python/django/belt_reviewer/belt_reviewer/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include("apps.my_app.urls", namespace='my_app'))
]

4-Python/django/belt_reviewer/apps/my_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
# from ..login.models import *
from django.db import models
import bcrypt, re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
NAME_REGEX = re.compile(r'^[a-zA-Z ]+$')
ALIAS_REGEX = re.compile(r'^\w+$')
PASSWORD_REGEX = re.compile(r'^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$')

class UserManager(models.Manager):
    def login(self, postData):

        failed_authentication = False
        messages = []

        try:
            found_user = User.objects.get(email=postData['email'])
        except:
            found_user = False

        if len(postData['email']) < 1:
            messages.append("Email cannot be left blank!")
            failed_authentication = True
        elif not EMAIL_REGEX.match(postData['email']):
            messages.append("Please enter a valid email!")
            failed_authentication = True
        elif not found_user:
            messages.append("No user found with this email address. Please register new user.")
            failed_authentication = True

        if failed_authentication:
            return {'result':"failed_authentication", 'messages':messages}
        if not PASSWORD_REGEX.match(postData['password']):
            messages.append("Password must be at least 8 characters with at least 1 uppercase letter and 1 numeric value")
            return {'result':"failed_authentication", 'messages':messages}

        hashed_password = bcrypt.hashpw(str(postData['password']), str(found_user.salt))

        if found_user.password != hashed_password:
            messages.append("Incorrect password! Please try again")
            failed_authentication = True


        if failed_authentication:
            return {'result':"failed_authentication", 'messages':messages}
        else:
            messages.append('Successfully logged in!')
            return {'result':'success', 'messages':messages, 'user':found_user}

    def register(self, postData):
        failed_validation = False
        messages = []
        if len(postData['full_name']) < 2:
            messages.append("Name must be at least 2 characters!")
            failed_validation = True
        elif not NAME_REGEX.match(postData['full_name']):
            messages.append("Name can only contain letters or spaces!")
            failed_validation = True
        if len(postData['alias']) < 2:
            messages.append("Alias must be at least 2 characters!")
            failed_validation = True
        elif not ALIAS_REGEX.match(postData['alias']):
            messages.append("Invalid Alias!")
            failed_validation = True
        try:
            found_user = User.objects.get(email=postData['email'])
        except:
            found_user = False
        if len(postData['email']) < 1:
            messages.append("Email is required!")
            failed_validation = True
        elif not EMAIL_REGEX.match(postData['email']):
            messages.append("Please enter a valid email!")
            failed_validation = True
        elif found_user:
            messages.append("This email is already registered!")
            failed_validation = True
        if len(postData['password']) < 1:
            messages.append("Password is required!")
            failed_validation = True
        elif not PASSWORD_REGEX.match(postData['password']):
            messages.append("Password must be at least 8 characters with at least 1 uppercase letter and 1 numeric value")
            failed_validation = True
        elif postData['confirm_password'] != postData['password']:
            messages.append("Password confirmation failed")
            failed_validation = True

        if failed_validation:
            return {'result':"failed_validation", 'messages':messages}
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(str(postData['password']), str(salt))
        User.objects.create(full_name=postData['full_name'], alias=postData['alias'], email=postData['email'], password=hashed_password, salt=salt)
        user = User.objects.get(email=postData['email'])
        return {'result':"Successfully registered new user", 'messages':messages, 'user':user}

class User(models.Model):
    full_name = models.CharField(max_length=45)
    alias = models.CharField(max_length=45)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    salt = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

class Author(models.Model):
    full_name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, related_name="books")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    users = models.ManyToManyField(User, related_name="books")

class Review(models.Model):
    content = models.TextField(max_length=1000)
    stars = models.IntegerField()
    book = models.ForeignKey(Book, related_name="reviews")
    user = models.ForeignKey(User, related_name="reviews")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

4-Python/django/belt_reviewer/apps/my_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.messages import get_messages
from django.contrib import messages
from django.db.models import Count
from django.core.urlresolvers import reverse
from .models import User, Book, Author, Review
# from .models import *

def index(request):
    context = {
        'messages':get_messages(request)
    }
    return render(request, "my_app/index.html", context)

def register(request):
    if request.method == "POST":
        post_data = {
            'full_name':request.POST['full_name'],
            'alias':request.POST['alias'],
            'email':request.POST['email'],
            'password':request.POST['password'],
            'confirm_password':request.POST['confirm_password']
        }
        register_result = User.objects.register(post_data)
        print register_result
        if register_result['result'] == "failed_validation":
            if 'messages' in register_result.keys():
                for message in register_result['messages']:
                    messages.error(request, message)
            return redirect('/')
        else:
            if 'user' in register_result.keys():
                request.session['current_user'] = register_result['user'].id
                if 'messages' in register_result.keys():
                    for message in register_result['messages']:
                        messages.success(request, message)
            else:
                messages.error(request, "Something went wrong")
                return redirect('/')
            return redirect('/landing_page')
    return redirect('/')

def landing_page(request):
    #response = "welcome to the landing page!"
    #return HttpResponse(response)
    context = {
        "messages":get_messages(request),
        "reviews":Review.objects.all().order_by('-created_at')[:3],
        "books":Book.objects.all().order_by('title')
    }
    if "current_user" in request.session.keys():
        context['user'] = User.objects.get(pk=request.session['current_user'])
    return render(request, "my_app/landing_page.html", context)

def login(request):
    if request.method == "POST":
        post_data = {
            'email':request.POST['email'],
            'password':request.POST['password']
        }
        login_result = User.objects.login(post_data)
        print login_result
        if login_result['result'] == "failed_authentication":
            print "login result returned failed authentication"
            if 'messages' in login_result.keys():
                for message in login_result['messages']:
                    messages.error(request, message)
            return redirect(reverse('my_app:index'))
        else:
            if 'user' in login_result.keys():
                request.session['current_user'] = login_result['user'].id
                # if 'messages' in login_result.keys():
                #     for message in login_result['messages']:
                #         messages.success(request, message)
            else:
                messages.error(request, "Something went wrong")
                return redirect(reverse('my_app:index'))
            print "*"*100
            return redirect(reverse('my_app:landing_page'))

def logout(request):
    request.session.clear()
    messages.success(request, "Successfully logged out")
    return redirect(reverse('my_app:index'))

def show_add_book_page(request):
    context = {
        "messages":get_messages(request),
        "authors":Author.objects.all
    }
    if "current_user" in request.session.keys():
        context['user'] = User.objects.get(pk=request.session['current_user'])
    return render(request, "my_app/add_book.html", context)

def process_add_book(request):
    if request.method == "POST":
        completed_form = True
        title = request.POST['title']
        if len(title) < 2:
            completed_form = False
            messages.error(request, "Title is required")
            print "Title is required"
        author = ""
        if request.POST['author-select'] != "":
            author = request.POST['author-select']
            print "found author in dropdown menu"
            print author
        else:
            author = request.POST['new-author']
            print "found new author"
            print author

            if author:
                try:
                    found = Author.objects.get(full_name=author)
                    print "Author already exists"
                    author = found.id
                except:
                    Author.objects.create(full_name=author)
                    author = Author.objects.get(full_name=author).id
                    messages.success(request, "Created new Author")
                    print "Created new author"
        if not author:
            completed_form = False
            messages.error(request, "Author is required")
            print "Author is required"
        content = request.POST['review']
        if len(content) < 2:
            completed_form = False
            messages.error(request, "Review is too short")
            print "Review is too short"
        stars = request.POST['rating']
        print "Title:", title
        print "Author ID:", author
        print "Review:", content
        print "Rating:", stars
        if completed_form:
            Book.objects.create(title=title, author=Author.objects.get(pk=int(author)))
            print "Created new book"
            book = Book.objects.get(title=title)
            user = User.objects.get(pk=request.session['current_user'])
            Review.objects.create(content=content, stars=stars, book=book, user=user)
            print "Added new review"
        else:
            messages.error(request, "please try again")
    return redirect(reverse('my_app:new_book'))

def show_book_page(request, book_id):
    book = Book.objects.get(pk=book_id)
    context = {
        "book":book,
        "reviews":Review.objects.filter(book=book)
    }
    return render(request, "my_app/book_page.html", context)

def show_user_profile(request, user_id):
    user = User.objects.get(pk=user_id)
    context = {
        "user":user,
        "reviews":Review.objects.filter(user=user),
        "reviewed_books":Book.objects.filter(reviews__user=user).distinct()
    }
    context['num_reviews'] = len(context['reviews'])
    return render(request, "my_app/user_profile.html", context)

def add_review(request, book_id):
    if request.method == "POST":
        content = request.POST['content']
        stars = request.POST['rating']
        user = User.objects.get(pk=request.session['current_user'])
        book = Book.objects.get(pk=book_id)
        Review.objects.create(content=content, stars=stars, user=user, book=book)
    return redirect(reverse('my_app:book_page', kwargs={'book_id':book_id}))

def delete_review(request, review_id):
    review = Review.objects.get(pk=review_id)
    book_id = review.book.id
    review.delete()
    # return redirect('/book/' + str(book_id))
    return redirect(reverse('my_app:book_page', kwargs={'book_id':book_id}))

def add_to_my_favorites(request, book_id):
    user = User.objects.get(pk=request.session['current_user'])
    book = Book.objects.get(pk=book_id)
    user.books.add(book)
    return redirect(reverse('my_app:landing_page'))

4-Python/django/belt_reviewer/apps/my_app/templates/my_app/add_book.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Adding New Book and Review</title>
  {% load staticfiles %}
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  <link rel="stylesheet" href="{% static 'my_app/css/styles.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
    crossorigin="anonymous">
</head>

<body>
  <a href="{% url 'my_app:landing_page' %}">Home</a> |
  <a href="{% url 'my_app:logout' %}">Logout</a>
  {% if messages %}
    {% for message in messages %}
    <p class="error">{{ message }}</p>
    {% endfor %}
  {% endif %}
  <h4>Add a New Book Title and a Review</h4>
  <form action="{% url 'my_app:process_add_book' %}" method="post">
    {% csrf_token %}
    <div class="box">
      <label for="title">Book Title:</label>
      <input type="text" name="title" value="">
      <br>
      <label>Author:</label>
      <br>
      <label for="author-select">Choose from the list:</label>
      <select name="author-select">
          <option> </option>
          {% for author in authors %}
          <option value="{{author.id}}">{{author.full_name}}</option>
          {% endfor %}
        </select>
      <br>
      <label for="new-author">Or add a new author:</label>
      <input type="text" name="new-author" value="">
      <label for="review">Review:</label>
      <textarea name="review"></textarea>
      <label for="rating">Rating:</label>
      <select name="rating">
        <option value="5">5</option>
        <option value="4">4</option>
        <option value="3">3</option>
        <option value="2">2</option>
        <option value="1">1</option>
      </select>
      <br>
      <input class="button" type="submit" name="" value="Add Book and Review">
    </div>
  </form>
</body>
</html>

4-Python/django/belt_reviewer/apps/my_app/templates/my_app/book_page.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{{book.title}}</title>
  {% load staticfiles %}
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  <link rel="stylesheet" href="{% static 'my_app/css/styles.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
    crossorigin="anonymous">
</head>

<body>
  <a href="{% url 'my_app:landing_page' %}">Home</a> |
  <a href="{% url 'my_app:logout' %}">Logout</a>
  <h3>{{book.title}}</h3>
  <a href="{% url 'my_app:add_to_my_favorites' book_id=book.id %}">Add to my favorites</a>
  <h4>Author: {{book.author.full_name}}</h4>
  <div class="box">
    <h4>Reviews:</h4>
    {% for review in reviews %}
    <p>Rating: {% for i in "x"|rjust:review.stars %}
    <img src="{% static 'my_app/img/star.png' %}" alt="star"> {% endfor %}</p>
    <p><a href="{% url 'my_app:user_page' user_id=review.user.id %}">{{review.user.alias}}</a> says: <i>{{review.content}}</i></p>
    <p>Posted on {{review.created_at}} {% if review.user.id == request.session.current_user %}</p>
    <a href="{% url 'my_app:delete_review' review_id=review.id %}">Delete this Review</a> {% endif %}
    {% endfor %}
  </div>
  <div class="box">
    <h4>Add a review:</h4>
    <form action="{% url 'my_app:add_review' book_id=book.id %}" method="post">
      {% csrf_token %}
      <textarea name="content" placeholder="Your review here..."></textarea>
      <br>
      <p>Rating:
        <select name="rating">
              <option value="5">5</option>
              <option value="4">4</option>
              <option value="3">3</option>
              <option value="2">2</option>
              <option value="1">1</option>
            </select> stars.
      </p>
      <input class="button" type="submit" name="" value="Submit Review">
    </form>
  </div>
  <div class="box">
    <h4>Favorites:</h4>
    <ul>
    {% for user in book.users.all %}
      <li><a href="{% url 'my_app:user_page' user_id=user.id %}">{{user.alias}}</a></li>
    {% endfor %}
    </ul>
  </div>
</body>

</html>

4-Python/django/belt_reviewer/apps/my_app/templates/my_app/index.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Login Page</title>
  {% load staticfiles %}
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  <link rel="stylesheet" href="{% static 'my_app/css/styles.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>

<body>
    <h4>Welcome!</h4>

    {% if messages %}
      {% for message in messages %}
      <p class="error">{{ message }}</p>
      {% endfor %}
    {% endif %}

    <div class="box">
      <form action="/register" method="post">
        <h4>Register</h4>
        {% csrf_token %}
        <label for="full_name">Name:</label>
        <input type="text" name="full_name">
        <br>
        <br>
        <label for="alias">Alias:</label>
        <input type="text" name="alias">
        <br>
        <br>
        <label for="email">Email Address:</label>
        <input type="text" name="email">
        <br>
        <br>
        <label for="password">Password:</label>
        <input type="password" name="password">
        <br>
        <prompt>*Password should be at least 8 characters</prompt>
        <label for="confirm_password">Confirm PW:</label>
        <input type="password" name="confirm_password">
        <br>
        <br>
        <input class="button" type="submit" value="Register">
      </form>
    </div>

    <div class="box">
      <form action="/login" method="post">
        <h4>Login</h4>
        {% csrf_token %}
        <label for="email">Email Address:</label>
        <input type="text" name="email">
        <br>
        <br>
        <label for="password">Password:</label>
        <input type="password" name="password">
        <br>
        <br>
        <input class="button" type="submit" value="Login">
      </form>
    </div>

</body>
</html>

4-Python/django/belt_reviewer/apps/my_app/templates/my_app/landing_page.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Landing Page</title>
  {% load staticfiles %}
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  <link rel="stylesheet" href="{% static 'my_app/css/styles.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
    crossorigin="anonymous">
</head>
<body>
  <a href="{% url 'my_app:new_book' %}">Add Book and Review</a> |
  <a href="{% url 'my_app:logout' %}">Logout</a>
  <h4>Welcome {{user.full_name}}!</h4>
  <div class="box">
    <h4>Recent Book Reviews:</h4>
      {% for review in reviews %}
        <a href="{% url 'my_app:book_page' book_id=review.book.id %}">{{review.book.title}}</a>
        <p>Rating: {% for i in "x"|rjust:review.stars %}
        <img src="{% static 'my_app/img/star.png' %}" alt="star"> {% endfor %}</p>
        <p><a href="{% url 'my_app:user_page' user_id=review.user.id %}">{{review.user.alias}}</a> says: <i>{{review.content}}</i></p>
        <p>Posted on {{review.created_at}}</p>
      {% endfor %}
  </div>
  <div class="box">
    <h4>Other Books with Reviews:</h4>
      {% for book in books %}
      <p><a href="{% url 'my_app:book_page' book_id=book.id %}">{{book.title}}</a></p>
      {% endfor %}
  </div>
</body>
</html>

4-Python/django/belt_reviewer/apps/my_app/templates/my_app/user_profile.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Profile for {{user.alias}}</title>
  {% load staticfiles %}
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  <link rel="stylesheet" href="{% static 'my_app/css/styles.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
    crossorigin="anonymous">
</head>
  <body>
    <div id="wrapper">
      <div>
        <a href="{% url 'my_app:landing_page' %}">Home</a> |
        <a href="{% url 'my_app:new_book' %}">Add Book and Review</a> |
        <a href="{% url 'my_app:logout' %}">Logout</a>
      </div>
      <div class="box">
        <h4>User</h4>
        <p>Alias: {{user.alias}}</h4>
        <p>Name: {{user.full_name}}</p>
        <p>Email: {{user.email}}</p>
        <p>Total Reviews: {{num_reviews}}</p>
      </div>
      <div class="box">
        <h4>Posted reviews on the following books:</h4>
        <ul>
        {% for book in reviewed_books %}
          <li><a href="{% url 'my_app:book_page' book_id=book.id %}">{{book.title}}</a></li>
        {% endfor %}
        </ul>
      </div>
      <div class="box">
        <h4>Favorites:</h4>
        <ul>
        {% for book in user.books.all %}
          <li><a href="{% url 'my_app:book_page' book_id=book.id %}">{{book.title}}</a></li>
        {% endfor %}
        </ul>
      </div>
    </div>
  </body>
</html>